#!/usr/bin/env python3
"""
Build `jobs/push_all.lua` — a self-contained job that publishes the ENTIRE
NightLoop package from this repo into the live place.

This is the generic replacement for the three-file `make_push.py`: same tricks
it needed (new instances instead of in-place `.Source`, ASCII-only payload,
byte-count verification), plus:

  * every script of the package, not three - `nightloop/src/**` and
    `nightloop/client/**`, i.e. the Rojo tree of `default.project.json`
  * an FNV-1a 32 hash per file, computed here and re-checked on the installed
    source with the exact-in-double decomposition, so "installed" means
    byte-identical rather than "looks about right"
  * unchanged files are left untouched (and the job says so), so one Ctrl+Z
    undoes only what actually changed
  * `--dry` builds `jobs/push_all_dry.lua`: identical logic, no writes - the
    live-vs-repo diff for every file in one read-only pass
  * keeps the old instance's `Disabled` flag across a replacement

Usage:
    python3 jobs/make_push_all.py            -> jobs/push_all.lua
    python3 jobs/make_push_all.py --dry      -> jobs/push_all_dry.lua
    python3 relay/relay.py push --dry        # generate + run, from the sandbox
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from repo_hashes import MANIFEST, ROOT, digest, fnv1a32  # noqa: E402

OUT_REAL = os.path.join(ROOT, "jobs", "push_all.lua")
OUT_DRY = os.path.join(ROOT, "jobs", "push_all_dry.lua")

# where each manifest key lives in the place (key -> parent, name, className)
TREE = {
    "NightLoop.Atmosphere": ("ServerScriptService.NightLoop", "Atmosphere", "ModuleScript"),
    "NightLoop.Beam": ("ServerScriptService.NightLoop", "Beam", "ModuleScript"),
    "NightLoop.Bootstrap": ("ServerScriptService.NightLoop", "Bootstrap", "Script"),
    "NightLoop.Config": ("ServerScriptService.NightLoop", "Config", "ModuleScript"),
    "NightLoop.CrawlerRig": ("ServerScriptService.NightLoop", "CrawlerRig", "ModuleScript"),
    "NightLoop.Director": ("ServerScriptService.NightLoop", "Director", "ModuleScript"),
    "NightLoop.EntityBase": ("ServerScriptService.NightLoop", "EntityBase", "ModuleScript"),
    "NightLoop.Flash": ("ServerScriptService.NightLoop", "Flash", "ModuleScript"),
    "NightLoop.MonsterAnimator": ("ServerScriptService.NightLoop", "MonsterAnimator", "ModuleScript"),
    "NightLoop.MonsterRig": ("ServerScriptService.NightLoop", "MonsterRig", "ModuleScript"),
    "NightLoop.Net": ("ServerScriptService.NightLoop", "Net", "ModuleScript"),
    "NightLoop.Registry": ("ServerScriptService.NightLoop", "Registry", "ModuleScript"),
    "NightLoop.Signal": ("ServerScriptService.NightLoop", "Signal", "ModuleScript"),
    "NightLoop.Entities.Breathless": ("ServerScriptService.NightLoop.Entities", "Breathless", "ModuleScript"),
    "NightLoop.Entities.Crawl": ("ServerScriptService.NightLoop.Entities", "Crawl", "ModuleScript"),
    "NightLoop.Entities.Knocker": ("ServerScriptService.NightLoop.Entities", "Knocker", "ModuleScript"),
    "NightLoop.Entities.TickingMan": ("ServerScriptService.NightLoop.Entities", "TickingMan", "ModuleScript"),
    "NightLoop.Entities.Whisperer": ("ServerScriptService.NightLoop.Entities", "Whisperer", "ModuleScript"),
    "NightLoop.Entities.WindowMonster": ("ServerScriptService.NightLoop.Entities", "WindowMonster", "ModuleScript"),
    "NightLoop.Entities._Template": ("ServerScriptService.NightLoop.Entities", "_Template", "ModuleScript"),
    "NightLoopClient": ("StarterPlayer.StarterPlayerScripts", "NightLoopClient", "LocalScript"),
    "NightLoopFirstPerson": ("StarterPlayer.StarterPlayerScripts", "NightLoopFirstPerson", "LocalScript"),
}

HEADER = r'''--!nonstrict
--[==[
	jobs/%(out)s - GENERATED by jobs/make_push_all.py. Do not hand-edit;
	edit nightloop/src/* or nightloop/client/* and re-run the generator.

	%(purpose)s

	Every script of the package: %(count)d files - all modules under
	ServerScriptService.NightLoop (+ the Entities folder), the Bootstrap
	server Script, and both StarterPlayerScripts client scripts.

	Why it is shaped this way:
	  1. A changed file is replaced with a NEW instance and only then is the
	     old one destroyed. Studio caches require() per instance, so editing
	     .Source in place keeps serving the OLD module for the rest of the
	     session (AGENTS.md pitfall #1) - a "fixed" module would test
	     byte-identical to the broken one.
	  2. The payload is ASCII-only. Every non-ASCII byte travels as a
	     placeholder and is restored here, because the usual PowerShell route
	     (Set-Content -Encoding ascii, then the CLI reading with the platform
	     default encoding) silently corrupts them - and here the sources are
	     data, so a mangled em dash is real drift (CONNECT.md section 8).
	  3. Every installed script is checked against the repo's byte count AND
	     an FNV-1a 32 hash, recomputed here on the live source with the
	     exact-in-double decomposition (see fnv). "Installed" therefore means
	     byte-identical, not "looks right".
	  4. A file whose live source already matches is left completely alone.

	One job = one ChangeHistoryService recording = one Ctrl+Z.
]==]

local H = game:GetService("HttpService")

-- placeholder -> real UTF-8 bytes, restored after every source arrives
local FIX = {
%(fix)s
}

-- X4[i * 16 + j] = i XOR j, i, j in 0..15. Bitwise operators are avoided on
-- purpose: the checked-in luau-compile predates them (CONNECT.md section 8).
local X4 = {
	0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,
	1,0,3,2,5,4,7,6,9,8,11,10,13,12,15,14,
	2,3,0,1,6,7,4,5,10,11,8,9,14,15,12,13,
	3,2,1,0,7,6,5,4,11,10,9,8,15,14,13,12,
	4,5,6,7,0,1,2,3,12,13,14,15,8,9,10,11,
	5,4,7,6,1,0,3,2,13,12,15,14,9,8,11,10,
	6,7,4,5,2,3,0,1,14,15,12,13,10,11,8,9,
	7,6,5,4,3,2,1,0,15,14,13,12,11,10,9,8,
	8,9,10,11,12,13,14,15,0,1,2,3,4,5,6,7,
	9,8,11,10,13,12,15,14,1,0,3,2,5,4,7,6,
	10,11,8,9,14,15,12,13,2,3,0,1,6,7,4,5,
	11,10,9,8,15,14,13,12,3,2,1,0,7,6,5,4,
	12,13,14,15,8,9,10,11,4,5,6,7,0,1,2,3,
	13,12,15,14,9,8,11,10,5,4,7,6,1,0,3,2,
	14,15,12,13,10,11,8,9,6,7,4,5,2,3,0,1,
	15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0
}

local function xor8(a, b)
	local hi = X4[(a // 16) * 16 + (b // 16) + 1]
	local lo = X4[(a %% 16) * 16 + (b %% 16) + 1]
	return hi * 16 + lo
end

-- FNV-1a 32, with the multiply decomposed as 16777619 = 2^24 + 2^8 + 147 so
-- every intermediate stays below 2^41 and is exact in a double. A naive
-- h * 16777619 with h < 2^32 exceeds 2^53 and rounds (verified 2026-10-07).
local function fnv(s)
	local h = 2166136261
	for i = 1, #s do
		local lo = h %% 256
		h = h - lo + xor8(lo, s:byte(i))
		h = (h * 147 + h * 256 + (h %% 256) * 16777216) %% 4294967296
	end
	return h
end

local DRY = %(dry)s

local FILES = {
%(files)s}

local function repair(s)
	for token, bytes in pairs(FIX) do
		s = s:gsub(token, bytes)
	end
	return s
end

local function resolve(path)
	local node = game
	for part in string.gmatch(path, "[^%%.]+") do
		node = node:FindFirstChild(part)
		if not node then
			return nil
		end
	end
	return node
end

local madeDirs = {}
local function ensureFolder(path)
	local node = game
	local trail = {}
	for part in string.gmatch(path, "[^%%.]+") do
		table.insert(trail, part)
		local nxt = node:FindFirstChild(part)
		if not nxt then
			if DRY then
				table.insert(madeDirs, table.concat(trail, ".") .. " (would create)")
				return nil
			end
			nxt = Instance.new("Folder")
			nxt.Name = part
			nxt.Parent = node
			table.insert(madeDirs, table.concat(trail, "."))
		end
		node = nxt
	end
	return node
end
'''

BODY = r'''
local report = {
	files = {},
	foldersCreated = madeDirs,
	dryRun = DRY,
	checks = { a = fnv("a") == 3826002220, hello = fnv("hello") == 1335831723 },
}
local counts = {}

local function bump(action)
	counts[action] = (counts[action] or 0) + 1
end

for _, entry in ipairs(FILES) do
	local src = repair(entry.src)
	local _, left = src:gsub("@@U", "")
	local row = {
		key = entry.key,
		parent = entry.parent,
		name = entry.name,
		class = entry.class,
		expect = entry.bytes,
		expectHash = entry.hash,
		remainingPlaceholders = left,
	}

	local parent = resolve(entry.parent)
	if not parent and not DRY then
		parent = ensureFolder(entry.parent)
	end

	if left > 0 then
		row.action = "SKIPPED"
		row.error = "placeholder survived the payload - refusing to install"
	elseif not parent then
		row.action = "SKIPPED"
		row.error = "parent missing: " .. entry.parent
	else
		local existing = parent:FindFirstChild(entry.name)
		local oldSource = nil
		if existing and existing:IsA("LuaSourceContainer") then
			local ok, s = pcall(function()
				return existing.Source
			end)
			if ok then
				oldSource = s
			end
		end
		row.existing = existing and existing.ClassName or nil
		row.oldBytes = oldSource and #oldSource or nil
		row.oldHash = oldSource and fnv(oldSource) or nil

		if DRY then
			if not existing then
				row.action = "would-create"
			elseif oldSource == src and existing.ClassName == entry.class then
				row.action = "unchanged"
			else
				row.action = "would-replace"
			end
		elseif existing and oldSource == src and existing.ClassName == entry.class then
			row.action = "unchanged"
		else
			local keptDisabled = nil
			if existing then
				if existing:IsA("BaseScript") then
					keptDisabled = existing.Disabled
				end
				row.before = { className = existing.ClassName, bytes = row.oldBytes, hash = row.oldHash }
			end
			local inst = Instance.new(entry.class)
			inst.Name = entry.name .. "__push"
			inst.Source = src
			inst.Parent = parent
			if existing then
				existing:Destroy()
			end
			inst.Name = entry.name
			if keptDisabled ~= nil and inst:IsA("BaseScript") then
				inst.Disabled = keptDisabled
				row.keptDisabled = keptDisabled
			end
			row.action = row.before and "replaced" or "created"
		end

		local live = parent:FindFirstChild(entry.name)
		if live and live:IsA("LuaSourceContainer") then
			local ok, s = pcall(function()
				return live.Source
			end)
			row.liveBytes = ok and #s or nil
			row.liveHash = ok and fnv(s) or nil
			row.bytesOk = row.liveBytes == entry.bytes
			row.hashOk = row.liveHash == entry.hash
			row.className = live.ClassName
		end
		if not DRY and (row.bytesOk == false or row.hashOk == false) then
			row.action = "FAILED"
		end
	end

	bump(row.action)
	table.insert(report.files, row)
end

-- Does the freshly installed code actually load, and what does it say?
local nl = resolve("ServerScriptService.NightLoop")
report.require = {}
if not DRY and nl then
	local function probe(path)
		local inst = resolve(path)
		if not inst then
			return { ok = false, error = "missing" }
		end
		local ok, res = pcall(require, inst)
		return { ok = ok, error = ok and nil or tostring(res) }
	end
	report.require.config = probe("ServerScriptService.NightLoop.Config")
	report.require.windowMonster = probe("ServerScriptService.NightLoop.Entities.WindowMonster")
	report.require.director = probe("ServerScriptService.NightLoop.Director")

	if report.require.config.ok then
		local okCfg, cfg = pcall(require, nl.Config)
		if okCfg and type(cfg) == "table" then
			local ents = cfg.Entities or {}
			local wm = ents.WindowMonster or {}
			local wh = ents.Whisperer or {}
			report.tuning = {
				showPhase = cfg.Hud and cfg.Hud.ShowPhase,
				nightDuration = cfg.NightDuration,
				windowMonster = { enabled = wm.Enabled, turnSpeed = wm.TurnSpeed },
				climbing = wm.Climbing ~= nil,
				climbSpeed = wm.Climbing and wm.Climbing.Speed,
				whispererEnabled = wh.Enabled,
				whispererVoiceIds = wh.WhisperSoundIds and #wh.WhisperSoundIds or 0,
				whispererGlassIds = wh.FakeGlassSoundIds and #wh.FakeGlassSoundIds or 0,
			}
		end
	end
end

report.summary = counts
report.ok = report.checks.a and report.checks.hello and (counts.FAILED or 0) == 0
	and (counts.SKIPPED or 0) == 0
if DRY then
	report.ok = report.checks.a and report.checks.hello
end

return H:JSONEncode(report)
'''

FILE_TMPL = """\t{
\t\tkey = "%(key)s",
\t\tparent = "%(parent)s",
\t\tname = "%(name)s",
\t\tclass = "%(class)s",
\t\tbytes = %(bytes)d,
\t\thash = %(hash)d,
\t\tsrc = [=====[
%(src)s]=====],
\t},
"""


def utf8_escapes(text):
    """Lua source with every non-ASCII byte escaped, plus the placeholder map."""
    out = []
    fixes = {}
    for ch in text:
        code = ord(ch)
        if code < 128:
            out.append(ch)
            continue
        token = "@@U%04X@@" % code
        if token not in fixes:
            fixes[token] = "".join("\\%d" % b for b in ch.encode("utf-8"))
        out.append(token)
    return "".join(out), fixes


def build(dry):
    files, all_fixes = [], {}
    for rel, key in MANIFEST:
        parent, name, cls = TREE[key]
        with open(os.path.join(ROOT, rel), encoding="utf-8") as fh:
            raw = fh.read()
        if "]=====]" in raw:
            raise SystemExit(f"{rel}: contains the long-string terminator ]=====]")
        src, fixes = utf8_escapes(raw)
        for token in fixes:
            if token in raw:
                raise SystemExit(f"{rel}: contains the literal placeholder {token}")
        all_fixes.update(fixes)
        fnv_hash, size = digest(rel)   # digest() returns (hash, bytes)
        files.append(FILE_TMPL % {
            "key": key, "parent": parent, "name": name, "class": cls,
            "bytes": size, "hash": fnv_hash, "src": src,
        })

    fix = "\n".join('\t["%s"] = "%s",' % (tok, esc) for tok, esc in sorted(all_fixes.items()))
    purpose = ("DRY RUN: reports, for every file, whether the live copy differs from the repo -\n"
               "\tand writes NOTHING. Run jobs/push_all.lua to actually publish." if dry else
               "Publishes the repo's NightLoop package into the LIVE place, replacing only the\n"
               "\tfiles whose source actually differs.")
    body = HEADER % {
        "out": "push_all_dry.lua" if dry else "push_all.lua",
        "purpose": purpose,
        "count": len(files),
        "fix": fix,
        "dry": "true" if dry else "false",
        "files": "\n".join(files) + "\n",
    } + BODY

    bad = [(i, c) for i, c in enumerate(body) if ord(c) > 127]
    if bad:
        raise SystemExit(f"job file is not ASCII at {bad[:5]}")
    return body


# ---------------------------------------------------------------------------
# payload verification - run after every build, no Studio needed
# ---------------------------------------------------------------------------

import re  # noqa: E402


def _lua_bytes(escaped):
    """Turn a Lua short-string body into bytes the way Luau would."""
    out = bytearray()
    i = 0
    while i < len(escaped):
        if escaped[i] == "\\" and i + 1 < len(escaped) and escaped[i + 1].isdigit():
            j = i + 1
            while j < len(escaped) and j < i + 4 and escaped[j].isdigit():
                j += 1
            out.append(int(escaped[i + 1:j]) & 0xFF)
            i = j
        else:
            out.extend(escaped[i].encode("utf-8"))
            i += 1
    return bytes(out)


FIX_RE = re.compile(r'\["(@@U[0-9A-F]{4}@@)"\] = "((?:\\\d{1,3})*)",')
ENTRY_RE = re.compile(
    r'key = "(?P<key>[^"]+)",.*?'
    r'bytes = (?P<bytes>\d+),\s*'
    r'hash = (?P<hash>\d+),\s*'
    r'src = \[=====\[\n(?P<src>.*?)\]=====\],',
    re.S,
)


def verify(path):
    """Re-decode the generated payload and compare with the repo files."""
    text = open(path, encoding="ascii").read()
    fix = {token: _lua_bytes(raw) for token, raw in FIX_RE.findall(text)}
    entries = list(ENTRY_RE.finditer(text))
    if not entries:
        raise SystemExit(f"{path}: no entries found - verifier is out of date")

    problems = []
    for match in entries:
        key = match.group("key")
        rel = next((r for r, k in MANIFEST if k == key), None)
        if rel is None:
            problems.append(f"{key}: not in the manifest")
            continue
        payload = match.group("src").encode("ascii")
        for token, real in fix.items():
            payload = payload.replace(token.encode("ascii"), real)
        with open(os.path.join(ROOT, rel), "rb") as fh:
            repo = fh.read()
        want_bytes, want_hash = int(match.group("bytes")), int(match.group("hash"))
        if payload != repo:
            problems.append(f"{key}: payload differs from {rel} "
                            f"({len(payload)} vs {len(repo)} bytes)")
        if want_bytes != len(repo):
            problems.append(f"{key}: recorded size {want_bytes} != {len(repo)}")
        if want_hash != fnv1a32(repo):
            problems.append(f"{key}: recorded hash {want_hash} != {fnv1a32(repo)}")
    if len(entries) != len(MANIFEST):
        problems.append(f"{len(entries)} entries for {len(MANIFEST)} manifest files")
    if problems:
        print(f"FAILED verification of {path}:")
        for line in problems[:10]:
            print("  -", line)
        raise SystemExit(1)
    print(f"verified {path}: {len(entries)} payloads decode byte-identical to the repo")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry", action="store_true", help="build the read-only diff job")
    ap.add_argument("--both", action="store_true", help="build both jobs")
    ap.add_argument("--no-verify", action="store_true",
                    help="skip re-decoding the generated payload")
    args = ap.parse_args()

    targets = []
    if args.both:
        targets = [(False, OUT_REAL), (True, OUT_DRY)]
    elif args.dry:
        targets = [(True, OUT_DRY)]
    else:
        targets = [(False, OUT_REAL)]

    for dry, out in targets:
        body = build(dry)
        with open(out, "w", encoding="ascii", newline="\n") as fh:
            fh.write(body)
        print(f"wrote {out} ({len(body)} bytes, ASCII-only, {len(MANIFEST)} files)")
        if not args.no_verify:
            verify(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
