#!/usr/bin/env python3
"""
Build a self-contained, ASCII-only `push_*.lua` job for HANDS MODE.

Why this exists
---------------
The sandbox cannot reach the user's machine (CONNECT.md §4), so game code is
delivered as a job the user runs with `ab.ps1 runfile`. Two traps make that
harder than it looks:

  * `arena_studio.py runfile` opens the file with the platform default
    encoding (cp1252 on Windows), and the usual paste route is
    `Set-Content -Encoding ascii`. Anything non-ASCII in the job file
    therefore arrives mangled. Here that matters because the sources are
    DATA, not comments: a mangled em dash would silently make the live
    module differ from the repo file, which is exactly the kind of phantom
    drift that cost a whole session once (CONNECT.md §8 item 6).
    Fix: every non-ASCII byte is replaced with an ASCII placeholder in the
    payload and restored by the job itself with numeric escapes, then
    asserted back with byte counts (see EXPECT / DASHES / DOTS below).

  * `write_script` edits `.Source` in place, so Studio keeps serving the
    cached module for the rest of the session (AGENTS.md pitfall #1). The
    job therefore creates NEW ModuleScripts and destroys the old ones.

Usage:  python3 jobs/make_push.py            -> jobs/push_climb.lua
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# (repo file, key) - the modules this push replaces.
MODULES = [
    ("nightloop/src/Config.lua", "Config"),
    ("nightloop/src/MonsterAnimator.lua", "MonsterAnimator"),
    ("nightloop/src/Entities/WindowMonster.lua", "WindowMonster"),
]

OUT = os.path.join(ROOT, "jobs", "push_climb.lua")

# non-ASCII byte -> placeholder. Kept explicit so the job file stays ASCII.
FIXES = {
    0xB7: ("@@U00B7@@", r"\194\183"),    # *
    0x2014: ("@@U2014@@", r"\226\128\148"),  # -
}

HEADER = """--!nonstrict
--[==[
\tjobs/push_climb.lua - GENERATED by jobs/make_push.py. Do not hand-edit;
\tedit nightloop/src/* and re-run the generator.

\tPushes the Watcher's climbing animation into the LIVE place:
\t  ServerScriptService.NightLoop.Config
\t  ServerScriptService.NightLoop.MonsterAnimator
\t  ServerScriptService.NightLoop.Entities.WindowMonster

\tTwo things this job is careful about:

\t1. It creates NEW ModuleScript instances and destroys the old ones rather
\t   than editing .Source in place. Studio caches require() per instance, so
\t   an in-place edit keeps serving the OLD module for the rest of the
\t   session (AGENTS.md pitfall #1) and a "fixed" module tests byte-identical
\t   to the broken one.
\t2. The payload is ASCII-only. Non-ASCII bytes are carried as placeholders
\t   and restored here, then counted, because PowerShell's usual
\t   `Set-Content -Encoding ascii` (and the CLI's default-encoding read)
\t   would otherwise silently corrupt the source on its way in.

\tSafe to re-run. One job = one ChangeHistoryService recording = one Ctrl+Z.
]==]

local H = game:GetService("HttpService")

-- placeholder -> real UTF-8 bytes, restored after the file has been read
local FIX = {
%(fix)s
}

-- integrity targets, measured on the repo files by the generator. If a byte
-- count or a character count comes back wrong, the file was mangled in
-- transit and the module must NOT be trusted.
local EXPECT = {%(expect)s}
local DASHES = {%(dashes)s}
local DOTS   = {%(dots)s}

local SOURCES = {}
%(sources)s

local function repair(s)
\tfor token, bytes in pairs(FIX) do
\t\ts = s:gsub(token, bytes)
\tend
\treturn s
end

local function count(haystack, needle)
\tlocal _, n = haystack:gsub(needle, "")
\treturn n
end

local nl = game:GetService("ServerScriptService"):FindFirstChild("NightLoop")
if not nl then
\treturn H:JSONEncode({ error = "no ServerScriptService.NightLoop - nothing pushed" })
end
local entities = nl:FindFirstChild("Entities")
if not entities then
\treturn H:JSONEncode({ error = "no ServerScriptService.NightLoop.Entities - nothing pushed" })
end

-- Replace a module: build the new instance FIRST, then drop the old one, so
-- the folder is never briefly without a module of that name.
local function put(parent, name, source)
\tlocal old = parent:FindFirstChild(name)
\tlocal inst = Instance.new("ModuleScript")
\tinst.Name = name .. "__push"
\tinst.Source = source
\tinst.Parent = parent
\tif old then
\t\told:Destroy()
\tend
\tinst.Name = name
\treturn inst
end

local written = {}
local function push(key, parent, name)
\tlocal src = repair(SOURCES[key])
\tlocal inst = put(parent, name, src)
\twritten[key] = inst
\treturn {
\t\tname = name,
\t\tpath = inst:GetFullName(),
\t\tbytes = #inst.Source,
\t\texpect = EXPECT[key],
\t\tbytesOk = #inst.Source == EXPECT[key],
\t\tdashes = count(inst.Source, "\\226\\128\\148"),
\t\tdashesOk = count(inst.Source, "\\226\\128\\148") == DASHES[key],
\t\tdots = count(inst.Source, "\\194\\183"),
\t\tdotsOk = count(inst.Source, "\\194\\183") == DOTS[key],
\t}
end

local report = {
\tpushed = {
\t\tpush("Config", nl, "Config"),
\t\tpush("MonsterAnimator", nl, "MonsterAnimator"),
\t\tpush("WindowMonster", entities, "WindowMonster"),
\t},
}

-- Did it land, and does the new Config actually parse and expose the new
-- block? require() on a plugin thread is the cheapest way to know.
local okConfig, liveConfig = pcall(require, nl.Config)
local okEntity, liveEntity = pcall(require, entities.WindowMonster)
report.require = {
\tconfig = okConfig,
\twindowMonster = okEntity,
\tconfigError = okConfig and nil or tostring(liveConfig),
\tentityError = okEntity and nil or tostring(liveEntity),
}
if okConfig then
\tlocal wm = liveConfig.Entities and liveConfig.Entities.WindowMonster
\tlocal climb = wm and wm.Climbing
\treport.climbing = {
\t\tpresent = climb ~= nil,
\t\tenabled = climb and climb.Enabled,
\t\tspeed = climb and climb.Speed,
\t\tstride = climb and climb.Stride,
\t\tgrip = climb and climb.Grip,
\t\tturnSpeed = wm and wm.TurnSpeed,
\t\trequireGround = wm and wm.RequireGround,
\t\tuseBuiltInRig = wm and wm.UseBuiltInRig,
\t}
end

local allOk = true
for _, entry in ipairs(report.pushed) do
\tif not (entry.bytesOk and entry.dashesOk and entry.dotsOk) then
\t\tallOk = false
\tend
end
report.ok = allOk and okConfig and okEntity

return H:JSONEncode(report)
"""

SOURCE_TMPL = """
SOURCES["%(key)s"] = [=====[
%(src)s
]=====]
"""


def tokenize(src):
    out = []
    for ch in src:
        code = ord(ch)
        if code in FIXES:
            out.append(FIXES[code][0])
        elif code > 127:
            raise SystemExit(f"unhandled non-ASCII char U+{code:04X} - add it to FIXES")
        else:
            out.append(ch)
    return "".join(out)


def main():
    sources = []
    expect, dashes, dots = [], [], []
    for rel, key in MODULES:
        path = os.path.join(ROOT, rel)
        raw = open(path, encoding="utf-8").read()
        if "]" + "=" * 5 + "]" in raw:
            raise SystemExit(f"{rel}: contains the long-string terminator ]=====]")
        expect.append(f'{key} = {len(raw.encode("utf-8"))}')
        dashes.append(f'{key} = {raw.count(chr(0x2014))}')
        dots.append(f'{key} = {raw.count(chr(0xB7))}')
        sources.append(SOURCE_TMPL % {"key": key, "src": tokenize(raw)})

    fix = "\n".join(f'\t["{tok}"] = "{esc}",' for tok, esc in FIXES.values())

    body = HEADER % {
        "fix": fix,
        "expect": ", ".join(expect),
        "dashes": ", ".join(dashes),
        "dots": ", ".join(dots),
        "sources": "".join(sources),
    }

    open(OUT, "w", encoding="ascii", newline="\n").write(body)

    bad = [(i, c) for i, c in enumerate(body) if ord(c) > 127]
    if bad:
        raise SystemExit(f"job file is not ASCII: {bad[:5]}")
    print(f"wrote {OUT} ({len(body)} bytes, ASCII-only) for: "
          + ", ".join(k for _, k in MODULES))
    return 0


if __name__ == "__main__":
    sys.exit(main())
