--!nonstrict
--[==[
	jobs/push_climb.lua - GENERATED by jobs/make_push.py. Do not hand-edit;
	edit nightloop/src/* and re-run the generator.

	Pushes the Watcher's climbing animation into the LIVE place:
	  ServerScriptService.NightLoop.Config
	  ServerScriptService.NightLoop.MonsterAnimator
	  ServerScriptService.NightLoop.Entities.WindowMonster

	Two things this job is careful about:

	1. It creates NEW ModuleScript instances and destroys the old ones rather
	   than editing .Source in place. Studio caches require() per instance, so
	   an in-place edit keeps serving the OLD module for the rest of the
	   session (AGENTS.md pitfall #1) and a "fixed" module tests byte-identical
	   to the broken one.
	2. The payload is ASCII-only. Non-ASCII bytes are carried as placeholders
	   and restored here, then counted, because PowerShell's usual
	   `Set-Content -Encoding ascii` (and the CLI's default-encoding read)
	   would otherwise silently corrupt the source on its way in.

	Safe to re-run. One job = one ChangeHistoryService recording = one Ctrl+Z.
]==]

local H = game:GetService("HttpService")

-- placeholder -> real UTF-8 bytes, restored after the file has been read
local FIX = {
	["@@U00B7@@"] = "\194\183",
	["@@U2014@@"] = "\226\128\148",
}

-- integrity targets, measured on the repo files by the generator. If a byte
-- count or a character count comes back wrong, the file was mangled in
-- transit and the module must NOT be trusted.
local EXPECT = {Config = 8357, MonsterAnimator = 12707, WindowMonster = 25219}
local DASHES = {Config = 2, MonsterAnimator = 1, WindowMonster = 13}
local DOTS   = {Config = 1, MonsterAnimator = 1, WindowMonster = 1}

local SOURCES = {}

SOURCES["Config"] = [=====[
--!nonstrict
--[[
	NightLoop @@U00B7@@ Config
	Every tunable in the package lives here. Nothing else should hold magic numbers.

	Porting to another game? This file plus Entities/ is usually all you touch.
]]

local Config = {}

-- ======== RUN MODE ========
-- "OneNight" : run a single night, fire NightEnded, stop.   <- reusable mode
-- "Endless"  : chain nights, scaling difficulty each time.
Config.Mode = "OneNight"

-- Start automatically when the server boots. Set false if your own code calls
-- Director:StartNight() (lobby, round system, another game, etc).
Config.AutoStart = true

-- Seconds. The design doc is 5 phases over 15 minutes.
Config.NightDuration = 900

-- Endless mode only: each subsequent night multiplies intensity by this.
Config.EndlessIntensityStep = 0.15
Config.EndlessMaxIntensity = 2.0

-- ======== PHASES ========
-- Start = seconds into the night. Intensity 0..1 drives entity aggression.
Config.Phases = {
	{ Name = "Unease",         Start = 0,   Intensity = 0.15 },
	{ Name = "Tension Builds", Start = 180, Intensity = 0.35 },
	{ Name = "House Awake",    Start = 360, Intensity = 0.55 },
	{ Name = "Overload",       Start = 540, Intensity = 0.78 },
	{ Name = "Breaking Point", Start = 720, Intensity = 1.00 },
}

-- ======== SHARED WORLD REFERENCES ========
-- Everything the package touches in YOUR place is named here, so porting means
-- editing strings rather than hunting through code.
Config.World = {
	SpotsFolder = "Spots",            -- Workspace.<name>, BaseParts
	FlashlightToolName = "Flashlight", -- Tool in the character
	FlashlightLightPart = "Light",     -- part inside the tool
	FlashlightAttachment = "LightOrigin",
	FlashlightBeamName = "Light",      -- the SpotLight inside the attachment
}

-- ======== SURVIVAL ========
-- How the night is lost. Per the design doc: the Window Monster breaching too
-- many times, or another entity landing a hit. Everything that can hurt the
-- player goes through Director:AddStrike, so the budget is shared.
Config.Survival = {
	MaxStrikes = 3,
	StrikeGrace = 2.5,  -- seconds of immunity after a strike, stops double hits
}

-- ======== ATMOSPHERE ========
-- Optional lighting control. Turn ControlLighting off and NightLoop will not
-- touch Lighting at all, which is what you want if your place already has its
-- own day/night system.
Config.Atmosphere = {
	ControlLighting = true,
	NightClockTime = 0,
	DawnClockTime = 6.6,
	DawnDuration = 8,     -- the payoff tween when the player survives
	NightBrightness = 0.35,
	DawnBrightness = 2,
	FogEasy = 320,        -- fog creeps in as intensity rises
	FogHard = 110,
}

-- ======== FLASH ========
-- The flashlight is a camera-style flash, not a held beam. Activating spends a
-- charge and fires one burst; charges refill on a timer.
Config.Flash = {
	Charges = 3,
	RechargeTime = 7,     -- seconds per charge
	BurstDuration = 0.14, -- how long the light stays on
	Cooldown = 0.5,       -- minimum seconds between flashes
	ZoomKick = 14,        -- degrees of FOV punch on the client

	-- A flash is brighter and reaches further than the resting torch. These
	-- override the SpotLight for the length of the burst and are restored
	-- after, so the hit cone always matches the light the player actually saw.
	BurstRange = 90,
	BurstBrightness = 8,
	BurstAngle = 0,       -- 0 = keep the light's own angle
}

-- ======== ENTITIES ========
-- Enabled=false entities are never required or ticked @@U2014@@ zero cost.
-- FirstPhase is 1-based index into Config.Phases.
Config.Entities = {
	WindowMonster = {
		Enabled = true,
		FirstPhase = 1,
		-- Built-in procedural rig: no asset IDs, no imports, animated by code.
		-- Set false to go back to cloning ServerStorage.<Template> instead.
		UseBuiltInRig = true,
		TurnSpeed = 2.0,        -- how fast the body swivels to keep facing you
		-- Never spawn at a spot with nothing under it. A spot qualifies if it
		-- has a floor within GroundSearch (it walks there) OR a surface it can
		-- climb (see Climbing, below).
		RequireGround = true,
		GroundSearch = 14,      -- how far below a spot to look for that floor

		-- Climbing: a spot with no floor used to be skipped outright, which is
		-- why the upper-floor windows stayed empty. With this on the Watcher
		-- scales the wall to reach them instead, in the open, where you can
		-- watch it coming. Needs UseBuiltInRig @@U2014@@ a template model has no climb
		-- pose to play.
		Climbing = {
			Enabled = true,
			Speed = 3.2,        -- studs/sec up the wall
			MinTime = 0.9,      -- a climb is never shorter than this
			MaxTime = 7,        -- ...nor longer; long climbs just go faster
			Search = 40,        -- how far below a spot to look for a way up
			Probe = 2.5,        -- how far sideways to look for the wall itself
			VoidRise = 9,       -- nothing below at all: it climbs this far up
			Grip = 0.4,         -- min gap kept between body and wall, stops clipping
			Stride = 2.4,       -- studs climbed per full arm/leg cycle
		},
		Template = "jumpscare",        -- ServerStorage.<name>, used when UseBuiltInRig = false
		-- beam repel
		RepelTimeEasy = 0.8,           -- seconds of light at intensity 0
		RepelTimeHard = 1.6,           -- ... at intensity 1
		DecayRate = 1.5,               -- exposure lost per second off target
		CheckInterval = 0.08,
		FadeMax = 0.65,
		RetreatCooldownEasy = 20,
		RetreatCooldownHard = 7,
		TeleportMinEasy = 9,
		TeleportMaxEasy = 16,
		TeleportMinHard = 3,
		TeleportMaxHard = 7,
		-- How long the monster sits at a window before it breaks in. This is the
		-- actual fail pressure: ignore it and you take a strike.
		BreachEasy = 34,       -- seconds of patience at intensity 0
		BreachHard = 9,        -- ... at intensity 1 ("glass shatters in seconds")
		BreachWarnAt = 0.45,   -- warn the player with this fraction left
		BreachRetreat = 6,     -- it drops back for this long after breaking in

		RangeTolerance = 1.05,
	},

	Whisperer = {
		Enabled = true,
		FirstPhase = 1,
		-- PASTE YOUR AUDIO IDS HERE. Without them the entity self-disables
		-- and tells you so in the output.
		WhisperSoundIds = {},          -- e.g. { "rbxassetid://123", ... }
		FakeGlassSoundIds = {},        -- phase 4+ misdirection
		IntervalEasy = 45,             -- seconds between cues at intensity 0
		IntervalHard = 9,              -- ... at intensity 1
		MinDistance = 12,              -- studs from the player
		MaxDistance = 34,
		Volume = 0.5,
		RollOffMax = 40,
	},

	Knocker = {
		Enabled = true,
		FirstPhase = 2,
		DoorPath = "Door",          -- Workspace.<name>, a BasePart
		IntervalEasy = 50,          -- seconds between knock sets at intensity 0
		IntervalHard = 14,          -- ... at intensity 1
		KnocksMin = 2,
		KnocksMax = 5,
		RattleStuds = 0.12,         -- how far the door jolts per knock
		RattleTime = 0.07,
		ScareRadius = 14,           -- stand this close during a knock and it reacts
		SlamFromPhase = 3,          -- phase at which knocks escalate to slams
		KnockSoundIds = {},         -- optional; rattle works without audio
		SlamSoundIds = {},
		Volume = 0.8,
		RollOffMax = 70,
	},
	Crawl = {
		Enabled = true,
		FirstPhase = 3,
		IntervalEasy = 55,      -- seconds between appearances at intensity 0
		IntervalHard = 18,      -- ... at intensity 1
		Speed = 18,             -- studs/sec across the surface (~1.4s per crossing)
		CeilingSearch = 30,     -- how far up to look for something to cling to
		WallSearch = 26,        -- fallback: how far sideways to look for a wall
		WallHeight = 5,         -- how high up the wall it runs
		SurfaceOffset = 0.45,   -- keeps the body from clipping into the surface
		MinRunDistance = 26,    -- length of a crossing
		DropFromPhase = 4,      -- phase at which it starts dropping into rooms
		DropChance = 0.45,
		HitRadius = 7,          -- stay this close after a drop...
		HitDelay = 1.6,         -- ...for this long, and it lands a strike
		Lifetime = 14,          -- max seconds on the floor before it leaves
		FleeSpeed = 48,
		RangeTolerance = 1.1,
	},
	Breathless  = { Enabled = false, FirstPhase = 4 },
	TickingMan  = { Enabled = false, FirstPhase = 5 },
}

-- ======== HUD ========
Config.Hud = {
	Enabled = true,
	ShowClock = true,
	ShowPhase = true,
	-- in-fiction clock: night runs from 12am to 6am across NightDuration
	ClockStartHour = 0,
	ClockEndHour = 6,
}

Config.Debug = false

return Config

]=====]

SOURCES["MonsterAnimator"] = [=====[
--!nonstrict
--[[
	NightLoop @@U00B7@@ MonsterAnimator

	Procedural animation for a Motor6D rig. No KeyframeSequences, no uploaded
	animation IDs @@U2014@@ poses are defined in code as per-joint CFrame offsets and
	blended toward every frame, with layered noise on top so the thing never
	holds perfectly still.

		local anim = MonsterAnimator.new(model)
		anim:Play("watch")       -- blends over time
		anim:Play("recoil", true) -- true = snap, no blend
		anim:Update(dt, targetPosition)
		anim:Destroy()

	States:
		idle     slow breathing, weight shifting
		watch    head tracks the nearest player, body stays unnaturally still
		twitch   a single hard jerk, auto-returns to the previous state
		recoil   flashed: head snaps away, arms shield the face
		lunge    breaching: surges toward the glass, jaw open
		climb    CYCLE, not a pose: hauling itself up a wall. Drive it with
		         SetCycle(phase) from the distance actually climbed, or the
		         limbs slide out of time with the body.
		retreat  folds down and away
]]

local MonsterAnimator = {}
MonsterAnimator.__index = MonsterAnimator

local MonsterRig = require(script.Parent.MonsterRig)

local function ang(x, y, z)
	return CFrame.Angles(math.rad(x or 0), math.rad(y or 0), math.rad(z or 0))
end

--[[
	A pose is joint name -> CFrame offset applied on top of the rig's rest C0.
	Anything not listed returns to rest.

	AXIS CONVENTION - the sign flips depending on which side of the joint the
	part sits, which is easy to get wrong:

	  Limbs hang BELOW their joint (arms, legs):
	      +X swings them FORWARD, -X back. +Z swings the RIGHT arm out,
	      -Z the left arm out. Knees bend on -X (shin goes backward).
	  Spine sits ABOVE its joint (Waist, Spine, NeckLower, Neck):
	      -X leans FORWARD, +X leans back. The opposite of the limbs.
	  Jaw hangs below the head joint, so +X opens it.

	Rotations COMPOUND down the chain: Waist, Spine and NeckLower each at 20
	degrees folds the body 60. Keep torso values small.
]]
--[=[
	climb is not a pose, it is a CYCLE. `cycle(phase, intensity)` returns the
	joint offsets for one point in the stride, phase in [0,1). The owner drives
	that phase from the distance the body has ACTUALLY climbed
	(MonsterAnimator:SetCycle) rather than from the clock, so the hands keep
	time with the wall. A clock-driven cycle visibly slides the moment the
	climb eases in, eases out, or changes speed.

	Same axis rules as every pose above. Arms reach UP at about +166 on X
	(they hang down at rest, so +90 is straight out in front and +180 is up),
	and the knee is drawn up by hip +X with the shin folded back by knee -X.
]=]
local function climbCycle(phase, intensity)
	local TAU = math.pi * 2
	local p = (phase or 0) % 1
	local effort = 0.55 + (intensity or 0) * 0.45

	-- 0 = hand overhead gripping, 0.5 = hand back down at the hip pulling
	local upR = (math.cos(TAU * p) + 1) * 0.5
	local upL = (math.cos(TAU * (p + 0.5)) + 1) * 0.5
	-- the knee comes up on the same side as the hand that is reaching
	local kneeR = (math.cos(TAU * (p + 0.25)) + 1) * 0.5
	local kneeL = (math.cos(TAU * (p + 0.75)) + 1) * 0.5
	local sway = math.sin(TAU * p) * 5

	return {
		-- pressed to the wall: hips in tight, shoulders working overhead
		RootJoint = CFrame.new(0, -0.1 - 0.08 * upR, 0.2),
		Waist = ang(-5, 0, sway * 0.5),
		Spine = ang(-4, 0, -sway * 0.4),
		NeckLower = ang(9, 0, 0),   -- chin up, watching the sill it is making for
		Neck = ang(-5, 0, 0),
		Jaw = ang(3 + effort * 7, 0, 0),

		ShoulderR = ang(24 + 142 * upR, 0, 11),
		ElbowR = ang(8 + 38 * upR, 0, 0),
		FingerR1 = ang(14 + 34 * (1 - upR), 0, 0),
		FingerR2 = ang(18 + 38 * (1 - upR), 0, 0),
		FingerR3 = ang(14 + 34 * (1 - upR), 0, 0),

		ShoulderL = ang(24 + 142 * upL, 0, -11),
		ElbowL = ang(8 + 38 * upL, 0, 0),
		FingerL1 = ang(14 + 34 * (1 - upL), 0, 0),
		FingerL2 = ang(18 + 38 * (1 - upL), 0, 0),
		FingerL3 = ang(14 + 34 * (1 - upL), 0, 0),

		HipR = ang(10 + 56 * kneeR, 0, 0),
		KneeR = ang(-16 - 88 * kneeR, 0, 0),
		AnkleR = ang(8 + 24 * kneeR, 0, 0),

		HipL = ang(10 + 56 * kneeL, 0, 0),
		KneeL = ang(-16 - 88 * kneeL, 0, 0),
		AnkleL = ang(8 + 24 * kneeL, 0, 0),
	}
end

local POSES = {
	idle = {
		blend = 2.2,
		joints = {
			Waist = ang(-2, 0, 0),
			Spine = ang(-3, 0, 0),
			NeckLower = ang(-6, 0, 0),  -- head carried forward, vulture-ish
			Neck = ang(3, 0, 0),        -- chin levelled back up
			ShoulderL = ang(3, 0, -6),
			ShoulderR = ang(3, 0, 6),
			ElbowL = ang(11, 0, 0),
			ElbowR = ang(11, 0, 0),
			KneeL = ang(-4, 0, 0),
			KneeR = ang(-4, 0, 0),
		},
	},

	-- the stare. Body locked rigid, only the head lives.
	watch = {
		blend = 3.0,
		joints = {
			Waist = ang(-1, 0, 0),
			Spine = ang(-2, 0, 0),
			NeckLower = ang(-10, 0, 0),
			Neck = ang(4, 0, 0),
			ShoulderL = ang(2, 0, -4),
			ShoulderR = ang(2, 0, 4),
			ElbowL = ang(8, 0, 0),
			ElbowR = ang(8, 0, 0),
			Jaw = ang(3, 0, 0),
		},
	},

	twitch = {
		blend = 26,
		hold = 0.13,
		joints = {
			Spine = ang(-2, 6, 0),
			NeckLower = ang(-8, 22, 0),
			Neck = ang(9, -15, 8),
			ShoulderR = ang(12, 0, 14),
			ElbowR = ang(22, 0, 0),
			Jaw = ang(9, 0, 0),
		},
	},

	-- caught in the beam: throws itself back, forearms up across the face
	recoil = {
		blend = 18,
		hold = 0.55,
		joints = {
			RootJoint = CFrame.new(0, 0, 0.4),
			Waist = ang(9, 0, 0),
			Spine = ang(7, 0, 0),
			NeckLower = ang(12, 0, 0),
			Neck = ang(5, 0, 0),
			Jaw = ang(22, 0, 0),
			ShoulderL = ang(70, 0, -14),
			ShoulderR = ang(70, 0, 14),
			ElbowL = ang(82, 0, 0),
			ElbowR = ang(82, 0, 0),
			FingerL1 = ang(26, 0, 0),
			FingerL2 = ang(30, 0, 0),
			FingerL3 = ang(26, 0, 0),
			FingerR1 = ang(26, 0, 0),
			FingerR2 = ang(30, 0, 0),
			FingerR3 = ang(26, 0, 0),
			HipL = ang(-6, 0, 0),
			HipR = ang(-6, 0, 0),
			KneeL = ang(-9, 0, 0),
			KneeR = ang(-9, 0, 0),
		},
	},

	-- coming through the window: drives forward, arms reaching, jaw wide
	lunge = {
		blend = 20,
		hold = 0.8,
		joints = {
			RootJoint = CFrame.new(0, 0, -0.8),
			Waist = ang(-13, 0, 0),
			Spine = ang(-9, 0, 0),
			NeckLower = ang(-13, 0, 0),
			Neck = ang(-3, 0, 0),
			Jaw = ang(36, 0, 0),
			ShoulderL = ang(70, 0, -13),
			ShoulderR = ang(70, 0, 13),
			ElbowL = ang(16, 0, 0),
			ElbowR = ang(16, 0, 0),
			FingerL1 = ang(38, 0, 0),
			FingerL2 = ang(44, 0, 0),
			FingerL3 = ang(38, 0, 0),
			FingerR1 = ang(38, 0, 0),
			FingerR2 = ang(44, 0, 0),
			FingerR3 = ang(38, 0, 0),
			HipL = ang(15, 0, 0),
			HipR = ang(-12, 0, 0),
			KneeL = ang(-22, 0, 0),
			KneeR = ang(-6, 0, 0),
		},
	},

	-- climbing the outside wall to reach a window with no floor under it.
	-- blend is high because the goal moves every frame; a slow blend would
	-- smear the cycle into a wobble.
	climb = {
		blend = 18,
		cycle = climbCycle,
	},

	-- folds down and away, curling forward over itself
	retreat = {
		blend = 5,
		joints = {
			RootJoint = CFrame.new(0, -0.3, 0.45),
			Waist = ang(-14, 0, 0),
			Spine = ang(-8, 0, 0),
			NeckLower = ang(-7, 0, 0),
			Neck = ang(-5, 0, 0),
			ShoulderL = ang(18, 0, -17),
			ShoulderR = ang(18, 0, 17),
			ElbowL = ang(54, 0, 0),
			ElbowR = ang(54, 0, 0),
			HipL = ang(24, 0, 0),
			HipR = ang(24, 0, 0),
			KneeL = ang(-42, 0, 0),
			KneeR = ang(-42, 0, 0),
			AnkleL = ang(18, 0, 0),
			AnkleR = ang(18, 0, 0),
		},
	},
}

function MonsterAnimator.new(model)
	local self = setmetatable({}, MonsterAnimator)
	self.model = model
	self.joints = MonsterRig.getJoints(model)

	-- rest pose, captured before anything moves
	self.rest = {}
	for name, m in pairs(self.joints) do
		self.rest[name] = m.C0
	end

	-- current blended offset per joint
	self.current = {}
	for name in pairs(self.joints) do
		self.current[name] = CFrame.new()
	end

	self.state = "idle"
	self.previous = "idle"
	self.holdUntil = 0
	self.clock = 0
	self.nextTwitch = 4 + math.random() * 7
	self.twitchEnabled = true
	self.intensity = 0
	self.cyclePhase = 0
	self.alive = true
	return self
end

-- Joint goals for a state, resolving cycling poses on the fly.
function MonsterAnimator:_goals(stateName)
	local pose = POSES[stateName]
	if not pose then
		return {}
	end
	if pose.cycle then
		return pose.cycle(self.cyclePhase, self.intensity)
	end
	return pose.joints
end

-- Where in the stride a cycling pose (climb) is, 0..1. Anything outside is
-- wrapped, so the caller can pass total distance / stride without a modulo.
function MonsterAnimator:SetCycle(phase)
	self.cyclePhase = (tonumber(phase) or 0) % 1
	return self.cyclePhase
end

function MonsterAnimator:Play(stateName, snap)
	if not POSES[stateName] or not self.alive then
		return
	end
	-- transient states remember where to fall back to
	if POSES[stateName].hold then
		if not POSES[self.state].hold then
			self.previous = self.state
		end
		-- self.clock, not os.clock(): Update is dt-driven, so holds must be too
		self.holdUntil = self.clock + POSES[stateName].hold
	else
		self.previous = stateName
		self.holdUntil = 0
	end

	self.state = stateName

	if snap then
		local goals = self:_goals(stateName)
		for name in pairs(self.joints) do
			self.current[name] = goals[name] or CFrame.new()
		end
	end
end

function MonsterAnimator:SetIntensity(value)
	self.intensity = math.clamp(value or 0, 0, 1)
end

-- Head tracking: aim the neck at a world position, clamped to a human-ish arc.
function MonsterAnimator:_look(targetPosition)
	local root = self.model.PrimaryPart
	if not root or not targetPosition then
		return CFrame.new(), CFrame.new()
	end

	local headJoint = self.joints.Neck
	local head = headJoint and headJoint.Part1
	local origin = head and head.Position or root.Position
	local localDir = root.CFrame:VectorToObjectSpace((targetPosition - origin).Unit)

	local yaw = math.atan2(-localDir.X, -localDir.Z)
	local pitch = math.asin(math.clamp(localDir.Y, -1, 1))

	-- split the turn between the two neck joints so it bends, not snaps
	yaw = math.clamp(yaw, math.rad(-105), math.rad(105))
	pitch = math.clamp(pitch, math.rad(-40), math.rad(45))

	-- NOT -pitch. The head sits ABOVE its joint, so -X pitches it DOWN (see the
	-- axis note on POSES). `pitch` is already negative for a target below, so
	-- passing it straight through looks down; negating it looked UP at the
	-- ceiling while the player stood below, which read as "staring past you".
	return CFrame.Angles(0, yaw * 0.45, 0),
		CFrame.Angles(pitch, yaw * 0.55, 0)
end

function MonsterAnimator:Update(dt, targetPosition)
	if not self.alive or not self.model.Parent then
		return
	end
	self.clock += dt

	-- transient states expire back to whatever was playing before
	if self.holdUntil > 0 and self.clock >= self.holdUntil then
		self.holdUntil = 0
		self.state = self.previous
	end

	local pose = POSES[self.state]
	if not pose then
		return
	end
	-- cycling poses rebuild their goals every frame from the current phase
	local target = self:_goals(self.state)
	local blend = math.clamp(pose.blend * dt, 0, 1)

	-- idle twitches, more often as the night gets worse
	if self.twitchEnabled and (self.state == "idle" or self.state == "watch") then
		self.nextTwitch -= dt * (1 + self.intensity * 2)
		if self.nextTwitch <= 0 then
			self.nextTwitch = 3 + math.random() * 8
			self:Play("twitch")
		end
	end

	-- breathing, and a tremor that grows with intensity
	local breathe = math.sin(self.clock * 1.15) * 0.016
	local sway = math.sin(self.clock * 0.42) * 0.9
	local tremor = self.intensity * 0.7

	local lookNeck, lookHead = CFrame.new(), CFrame.new()
	if self.state == "watch" and targetPosition then
		lookNeck, lookHead = self:_look(targetPosition)
	end

	for name, motor in pairs(self.joints) do
		local goal = target[name] or CFrame.new()

		if name == "NeckLower" then
			goal = goal * lookNeck
		elseif name == "Neck" then
			goal = goal * lookHead
		elseif name == "Spine" then
			goal = goal * CFrame.Angles(breathe, math.rad(sway * 0.4), 0)
		elseif name == "Waist" then
			goal = goal * CFrame.Angles(0, math.rad(sway * 0.6), math.rad(sway * 0.3))
		end

		-- per-joint jitter: tiny, random, never settles
		if tremor > 0 and (name == "Neck" or name == "NeckLower" or name == "Jaw") then
			local j = tremor * 0.012
			goal = goal * CFrame.Angles(
				(math.random() - 0.5) * j,
				(math.random() - 0.5) * j,
				(math.random() - 0.5) * j)
		end

		self.current[name] = self.current[name]:Lerp(goal, blend)
		motor.C0 = self.rest[name] * self.current[name]
	end
end

function MonsterAnimator:Destroy()
	self.alive = false
	-- put the rig back to rest so a reused model is never left mid-pose
	for name, motor in pairs(self.joints or {}) do
		if motor.Parent and self.rest[name] then
			motor.C0 = self.rest[name]
		end
	end
	self.joints = nil
	self.current = nil
end

MonsterAnimator.States = POSES

return MonsterAnimator

]=====]

SOURCES["WindowMonster"] = [=====[
--!nonstrict
--[[
	NightLoop @@U00B7@@ WindowMonster
	Moves between Workspace.Spots. Catch it in a single camera flash and
	it retreats @@U2014@@ one shot, no holding. Leave it at a window too long and it
	breaches, which costs a strike; enough strikes and the night is lost.

	A spot with a floor under it is walked to. A spot with nothing but wall
	under it is climbed to (Config.Entities.WindowMonster.Climbing): it blinks
	to the foot of the wall and hauls itself up where you can see it, which is
	what unlocked the upper-floor windows.

	Server-authoritative: subscribes to Flash.Fired, which only the server can
	raise. Detection cone is derived from SpotLight.Angle / .Range so the hitbox
	always matches the burst the player sees, and the ray punches through glass
	so flashing a monster through a window works.

	Scales with phase intensity: teleports faster, retreats for less time, and
	takes longer to repel as the night escalates.
]]

local Players = game:GetService("Players")
local ServerStorage = game:GetService("ServerStorage")
local Workspace = game:GetService("Workspace")

local EntityBase = require(script.Parent.Parent.EntityBase)
local Beam = require(script.Parent.Parent.Beam)
local MonsterRig = require(script.Parent.Parent.MonsterRig)
local MonsterAnimator = require(script.Parent.Parent.MonsterAnimator)

local WindowMonster = EntityBase.new("WindowMonster")

-- ---------------------------------------------------------------- validation
function WindowMonster:Validate(ctx)
	local world = ctx.Config.World
	local spots = Workspace:FindFirstChild(world.SpotsFolder)
	if not spots then
		return false, ("Workspace.%s not found"):format(world.SpotsFolder)
	end

	local count = 0
	for _, v in ipairs(spots:GetChildren()) do
		if v:IsA("BasePart") then
			count += 1
		end
	end
	if count == 0 then
		return false, ("Workspace.%s has no BaseParts"):format(world.SpotsFolder)
	end

	if not self.Settings.UseBuiltInRig then
		if not ServerStorage:FindFirstChild(self.Settings.Template) then
			return false, ("ServerStorage.%s not found"):format(self.Settings.Template)
		end
		self._template = ServerStorage[self.Settings.Template]
	end

	self._spotsFolder = spots

	if self.Settings.RequireGround then
		local usable = 0
		for _, v in ipairs(spots:GetChildren()) do
			if v:IsA("BasePart") and self:_classify(v) then
				usable += 1
			end
		end
		if usable == 0 then
			return false, ("no spot in %s has a floor within %d studs or anything to climb @@U2014@@ the Watcher walks or climbs, it does not hover. Lower the spots, add a floor, or set RequireGround = false")
				:format(world.SpotsFolder, self.Settings.GroundSearch)
		end
	end
	return true
end

-- -------------------------------------------------------------------- spots
--[=[
	What holds the Watcher up at a spot?

		mode = "ground" @@U2014@@ a floor within GroundSearch. It walks there, as before.
		mode = "climb"  @@U2014@@ no floor, but there is something to scale: it hangs on
		                  the wall (or a sill) and hauls itself up. `pos` is
		                  where the climb starts; `wall` is { normal, dist } for
		                  the vertical surface it clings to, normal pointing
		                  away from the wall.
		nil             @@U2014@@ nothing under it at all and climbing is off: skipped,
		                  because the Watcher walks or climbs, it does not hover.

	Cached: this is a handful of raycasts per spot and the house does not move
	during a night. Invalidated whenever a spot is added or removed.
]=]
function WindowMonster:_classify(spot)
	if not self._classifyCache then
		self._classifyCache = {}
	end
	local cached = self._classifyCache[spot]
	if cached == nil then
		cached = self:_probeSupport(spot) or false
		self._classifyCache[spot] = cached
	end
	if cached == false then
		return nil
	end
	return cached
end

local PROBE_DIRS = {
	Vector3.new(1, 0, 0), Vector3.new(-1, 0, 0),
	Vector3.new(0, 0, 1), Vector3.new(0, 0, -1),
	Vector3.new(0.7071, 0, 0.7071), Vector3.new(-0.7071, 0, 0.7071),
	Vector3.new(0.7071, 0, -0.7071), Vector3.new(-0.7071, 0, -0.7071),
}

function WindowMonster:_rayParams()
	local params = RaycastParams.new()
	params.FilterType = Enum.RaycastFilterType.Exclude
	local ignore = {}
	if self._monster then
		table.insert(ignore, self._monster)
	end
	for _, p in ipairs(Players:GetPlayers()) do
		if p.Character then
			table.insert(ignore, p.Character)
		end
	end
	params.FilterDescendantsInstances = ignore
	params.IgnoreWater = true
	return params
end

--[=[
	Is there a vertical surface within a body-width of the spot? Cast a ring
	outward and take the closest wall-like hit. The normal points AWAY from the
	wall, back toward the spot @@U2014@@ which is the direction the Watcher hangs, and
	therefore also the way its body faces once it gets there.
]=]
function WindowMonster:_wallNormal(spot)
	local climb = self.Settings.Climbing
	local reach = climb and climb.Probe or 2.5
	local params = self:_rayParams()
	local best, bestDist = nil, math.huge
	for _, dir in ipairs(PROBE_DIRS) do
		local hit = Workspace:Raycast(spot.Position, dir * reach, params)
		if hit and math.abs(hit.Normal.Y) < 0.5 and hit.Distance < bestDist then
			local flat = Vector3.new(hit.Normal.X, 0, hit.Normal.Z)
			if flat.Magnitude > 0.2 then
				best, bestDist = flat.Unit, hit.Distance
			end
		end
	end
	if not best then
		return nil
	end
	-- the probe direction and the surface normal are not parallel for a corner,
	-- so the measured distance is an upper bound on the true gap. Fine: Grip
	-- only ever nudges outward by a few tenths.
	return { normal = best, dist = bestDist }
end

function WindowMonster:_probeSupport(spot)
	local climb = self.Settings.Climbing
	local climbing = climb and climb.Enabled or false
	local reach = self.Settings.GroundSearch
	if climbing then
		reach = math.max(reach, climb.Search)
	end

	local params = self:_rayParams()
	local origin = spot.Position + Vector3.new(0, 2, 0)
	local down = Workspace:Raycast(origin, Vector3.new(0, -(reach + 2), 0), params)

	-- a floor within walking distance: it just stands there
	if down and down.Normal.Y > 0.5
		and (origin.Y - down.Position.Y) <= (self.Settings.GroundSearch + 2) then
		return { mode = "ground", pos = down.Position, drop = origin.Y - down.Position.Y }
	end

	if not climbing then
		return nil
	end

	-- No floor. A wall beside the spot is better evidence than whatever is far
	-- below it, and it also tells us which way to face on arrival.
	local wall = self:_wallNormal(spot)
	if not wall and down then
		local flat = Vector3.new(down.Normal.X, 0, down.Normal.Z)
		if flat.Magnitude > 0.2 then
			-- whatever it hit below is at least slanted; treat it as touching
			wall = { normal = flat.Unit, dist = 0 }
		end
	end

	-- Hanging over nothing at all: it climbs up out of the dark below. Rare,
	-- and the fog hides the cheat.
	local base = down and down.Position
		or (spot.Position - Vector3.new(0, climb.VoidRise, 0))

	return { mode = "climb", pos = base, wall = wall,
		drop = down and (origin.Y - down.Position.Y) or climb.VoidRise }
end

--[=[
	Nudge the body off the wall so it never clips the sill. The spot marks where
	the Watcher ends up; this only moves it when the spot sits closer to the
	wall than Climbing.Grip, so a sensibly placed spot is left alone.
]=]
function WindowMonster:_gripOffset(sup)
	local climb = self.Settings.Climbing
	if not (climb and sup and sup.wall) then
		return Vector3.new(0, 0, 0)
	end
	local gap = climb.Grip - sup.wall.dist
	if gap <= 0 then
		return Vector3.new(0, 0, 0)
	end
	return sup.wall.normal * gap
end

function WindowMonster:_spots()
	if self._spotCache and #self._spotCache > 0 then
		return self._spotCache
	end
	local out = {}
	local skipped = {}
	local byClimb = 0
	for _, v in ipairs(self._spotsFolder:GetChildren()) do
		if v:IsA("BasePart") then
			local sup = self:_classify(v)
			if self.Settings.RequireGround and not sup then
				table.insert(skipped, v.Name)
			else
				if sup and sup.mode == "climb" then
					byClimb += 1
				end
				table.insert(out, v)
			end
		end
	end
	self._climbSpots = byClimb
	if #skipped > 0 then
		self:Log(("ignoring %d spot(s) with nothing under them: %s")
			:format(#skipped, table.concat(skipped, ", ")))
	end
	self._spotCache = out
	return out
end

local function farthestFrom(pos, spots)
	local best, bestDist = nil, -math.huge
	for _, s in ipairs(spots) do
		local d = (s.Position - pos).Magnitude
		if d > bestDist then
			bestDist, best = d, s
		end
	end
	return best
end

-- ------------------------------------------------------------------- visuals
local function setHidden(model, hidden)
	if not model then
		return
	end
	local isRig = MonsterRig.isRig(model)
	for _, part in ipairs(model:GetDescendants()) do
		if part:IsA("BasePart") then
			-- a rig anchors ONLY its root; anchoring limbs freezes the Motor6Ds
			if isRig then
				part.Anchored = (part == model.PrimaryPart)
			else
				part.Anchored = true
			end
			-- A rig's limbs stay non-collidable even when shown: the body is
			-- dragged around by PivotTo (a climb sweeps it through space), and
			-- solid limbs would shove the player standing at the window.
			part.CanCollide = (not hidden) and (not isRig)
			local base = part:GetAttribute("BaseTransparency")
			part.Transparency = hidden and 1 or (base or 0)
		elseif part:IsA("Decal") or part:IsA("Texture") then
			part.Transparency = hidden and 1 or 0
		end
	end
end

local function setFade(model, alpha)
	if not model then
		return
	end
	for _, part in ipairs(model:GetDescendants()) do
		if part:IsA("BasePart") or part:IsA("Decal") or part:IsA("Texture") then
			part.Transparency = alpha
		end
	end
end

--[[
	Put the model at a spot, standing on the floor and turned to face whoever
	is nearest.

	The old version did `spot.CFrame + Vector3.new(0, 0.5, 0)`, which inherited
	the SPOT PART's orientation @@U2014@@ so the Watcher faced whatever arbitrary
	direction a 1x1x1 marker happened to point, usually away from the room.
	Head tracking is clamped to a human-ish arc, so it could never turn far
	enough to recover: it ended up staring off into a wall.
]]
-- Where the model's FEET sit for a given base point. The rig's pivot is at the
-- feet already, but a template model's may not be, so measure rather than guess.
function WindowMonster:_feetAt(model, base)
	local boxCF, boxSize = model:GetBoundingBox()
	local pivot = model:GetPivot()
	local pivotToBottom = pivot.Position.Y - (boxCF.Position.Y - boxSize.Y * 0.5)
	return Vector3.new(base.X, base.Y + pivotToBottom, base.Z)
end

--[=[
	The pose the Watcher holds once it is AT a spot: standing on a floor, or
	clinging to a wall with no floor under it.

	Clinging pushes the body out along the surface normal by Climbing.Grip and
	turns it to face INTO the wall @@U2014@@ which, at a window, means facing the room.
	That is the whole point of the climb: it arrives pressed to the glass.
]=]
function WindowMonster:_poseCFrame(model, spot, sup)
	local base = spot.Position
	local offset = self:_gripOffset(sup)

	if sup and sup.mode == "ground" then
		base = sup.pos
		offset = Vector3.new(0, 0, 0)
	end

	local pos = self:_feetAt(model, base) + offset

	if sup and sup.wall then
		-- face INTO the wall: at a window, that is facing the room
		return CFrame.lookAt(pos, pos - sup.wall.normal)
	end

	local target = self:_nearestPlayerTo(pos)
	if target then
		local flat = Vector3.new(target.X - pos.X, 0, target.Z - pos.Z)
		if flat.Magnitude > 0.25 then
			return CFrame.lookAt(pos, pos + flat.Unit)
		end
	end
	return CFrame.new(pos)
end

function WindowMonster:_placeAt(model, spot)
	if not (model and model.Parent and spot) then
		return
	end
	model:PivotTo(self:_poseCFrame(model, spot, self:_classify(spot)))
end

-- ------------------------------------------------------------------ climbing
--[=[
	Spots with no floor under them used to be skipped outright, which is why the
	upper-floor windows stayed empty all night. With climbing on, the Watcher
	scales the wall instead: it blinks out, reappears at the foot of the wall,
	and hauls itself up in plain sight. The climb is the tell @@U2014@@ you see it
	coming and you have that long to find it with the flash.

	You can hit it mid-climb. _flashHits accepts the "climbing" state, and a
	repel drops it off the wall (see _repel).
]=]
function WindowMonster:_climbingEnabled()
	local climb = self.Settings.Climbing
	return climb ~= nil and climb.Enabled == true and self.Settings.UseBuiltInRig
end

-- The pose it starts the climb from, at the bottom, facing the wall. Same X/Z
-- as the destination (the probe fell straight down), so it scales straight up.
function WindowMonster:_climbBaseCFrame(model, spot, sup, destination)
	local pos = self:_feetAt(model, sup.pos) + self:_gripOffset(sup)
	if sup.wall then
		return CFrame.lookAt(pos, pos - sup.wall.normal)
	end
	local look = Vector3.new(destination.LookVector.X, 0, destination.LookVector.Z)
	if look.Magnitude > 0.1 then
		return CFrame.lookAt(pos, pos + look.Unit)
	end
	return CFrame.new(pos)
end

function WindowMonster:_startClimb(spot, sup, ctx)
	local cfg = self.Settings.Climbing
	local monster = self._monster
	if not (cfg and monster) then
		return
	end

	local to = self:_poseCFrame(monster, spot, sup)
	local from = self:_climbBaseCFrame(monster, spot, sup, to)

	local rise = (to.Position - from.Position).Magnitude
	local speed = math.max(0.1, cfg.Speed)
	local dur = math.clamp(rise / speed, cfg.MinTime, cfg.MaxTime)

	-- blink to the bottom of the wall, then let it be seen on the way up
	setHidden(monster, true)
	monster:PivotTo(from)
	setHidden(monster, false)

	self._currentSpot = spot
	self._state = "climbing"
	self._climb = {
		from = from,
		to = to,
		t = 0,
		dur = dur,
		rise = rise,
		climbed = 0,
		last = from.Position,
	}

	-- The siege clock is paused for the duration: a slow climb should not cost
	-- the player patience they never had a chance to spend.
	if self._breachAt and self._breachAt > 0 then
		self._breachAt += dur
	end

	if self._animator then
		self._animator:Play("climb", true)
	end

	ctx.Net.BroadcastCue({
		kind = "climb",
		entity = self.Name,
		spot = spot.Name,
		seconds = dur,
	})
	self:Log(("climbing to %s @@U2014@@ %.1f studs in %.1fs"):format(spot.Name, rise, dur))
end

function WindowMonster:_cancelClimb()
	self._climb = nil
end

function WindowMonster:_updateClimb(dt, ctx)
	local c = self._climb
	local monster = self._monster
	if not (c and monster and monster.Parent) then
		self:_cancelClimb()
		self._state = "idle"
		return
	end

	local cfg = self.Settings.Climbing
	c.t += dt
	local alpha = math.clamp(c.t / c.dur, 0, 1)
	-- ease in and out; starting and stopping dead reads as a teleport
	local eased = alpha * alpha * (3 - 2 * alpha)

	local cf = c.from:Lerp(c.to, eased)
	monster:PivotTo(cf)

	-- drive the animation off distance actually covered, not the clock
	c.climbed += (cf.Position - c.last).Magnitude
	c.last = cf.Position
	if self._animator then
		self._animator:SetCycle(c.climbed / math.max(0.1, cfg.Stride))
	end

	if alpha >= 1 then
		self:_cancelClimb()
		self._state = "idle"
		if self._animator then
			self._animator:Play("watch", true)
		end
		-- give it a beat at the window before it moves on. NOTE: the teleport
		-- timings live on Settings, not on Settings.Climbing (cfg).
		local s = self.Settings
		local minWait = self:ByIntensity(s.TeleportMinEasy, s.TeleportMinHard, ctx.Intensity)
		local maxWait = self:ByIntensity(s.TeleportMaxEasy, s.TeleportMaxHard, ctx.Intensity)
		self._nextTeleport = os.clock() + minWait + math.random() * math.max(0, maxWait - minWait)
	end
end

-- Move to a spot: climb if it hangs, walk there if it does not.
-- RequireGround = false means "do not check, just put it there" @@U2014@@ that is the
-- old behaviour and it stays that way, so no surprise climbs appear for it.
function WindowMonster:_goTo(spot, ctx)
	local sup = self:_classify(spot)
	if sup and sup.mode == "climb" and self.Settings.RequireGround
		and self:_climbingEnabled() and self._animator then
		self:_startClimb(spot, sup, ctx)
		return
	end
	self:_placeAt(self._monster, spot)
	self._currentSpot = spot
end

-- --------------------------------------------------------------------- beam
-- A flash counts if the cone reaches the monster. Beam.castThrough ignores
-- see-through parts, so the windows in this house no longer eat the ray.
function WindowMonster:_flashHits(player, originCFrame, originPos, spot)
	if not self._monster then
		return false
	end
	-- on the wall counts: catch it halfway up and it loses its grip
	if self._state ~= "idle" and self._state ~= "climbing" then
		return false
	end
	local halfAngle = spot.Angle / 2
	local range = spot.Range * self.Settings.RangeTolerance
	return Beam.coneHitsTarget(originCFrame, originPos, halfAngle, range,
		self._monster, { player.Character })
end

-- ------------------------------------------------------------------ breach
-- Every appearance starts a countdown. Flash it in time and the countdown
-- dies with the appearance; let it run out and the monster gets in.
-- Pressure is a siege, not a per-window timer: it survives teleports and only
-- clears when the player actually repels it.
function WindowMonster:_armBreach(ctx)
	local cfg = self.Settings
	local patience = self:ByIntensity(cfg.BreachEasy, cfg.BreachHard, ctx.Intensity)
	self._breachAt = os.clock() + patience
	self._breachWarned = false
	self._patience = patience
end

function WindowMonster:_disarmBreach()
	self._breachAt = 0
	self._breachWarned = false
end

function WindowMonster:_breach(ctx)
	local monster = self._monster
	self:_disarmBreach()

	-- it got in: show it, then pull back so the player can recover
	ctx.Net.BroadcastCue({
		kind = "breach",
		entity = self.Name,
		spot = self._currentSpot and self._currentSpot.Name or nil,
	})

	ctx.Director:AddStrike("WindowMonster", {
		spot = self._currentSpot and self._currentSpot.Name or nil,
	})

	if self._animator then
		self._animator:Play("lunge", true)
	end

	-- let the lunge read before it vanishes
	task.delay(0.55, function()
		if monster and monster.Parent then
			setHidden(monster, true)
		end
	end)
	self._state = "hidden"
	self._retreatUntil = os.clock() + self.Settings.BreachRetreat
	self:Log("breach")
end

-- ---------------------------------------------------------------- lifecycle
function WindowMonster:_spawn(spot)
	local clone
	if self.Settings.UseBuiltInRig then
		clone = MonsterRig.build({ name = "WindowMonster_Active" })
	else
		clone = self._template:Clone()
	end
	clone.Name = "WindowMonster_Active"
	clone.Parent = Workspace

	if not clone.PrimaryPart then
		clone.PrimaryPart = clone:FindFirstChild("Body")
			or clone:FindFirstChild("HumanoidRootPart")
			or clone:FindFirstChildWhichIsA("BasePart")
	end

	local isRig = MonsterRig.isRig(clone)
	for _, p in ipairs(clone:GetDescendants()) do
		if p:IsA("BasePart") then
			p.Anchored = isRig and (p == clone.PrimaryPart) or not isRig
			p.CanCollide = not isRig
		end
	end

	self:_placeAt(clone, spot)
	self:Own(clone)

	if isRig then
		if self._animator then
			self._animator:Destroy()
		end
		self._animator = MonsterAnimator.new(clone)
		self._animator:Play("watch", true)
	end
	return clone
end

-- who the thing should be staring at
function WindowMonster:_nearestPlayer()
	local monster = self._monster
	if not monster or not monster.PrimaryPart then
		return nil
	end
	return self:_nearestPlayerTo(monster.PrimaryPart.Position)
end

function WindowMonster:_nearestPlayerTo(origin)
	local best, bestDist = nil, math.huge
	for _, player in ipairs(Players:GetPlayers()) do
		local char = player.Character
		local head = char and (char:FindFirstChild("Head") or char:FindFirstChild("HumanoidRootPart"))
		if head then
			local d = (head.Position - origin).Magnitude
			if d < bestDist then
				best, bestDist = head.Position, d
			end
		end
	end
	return best
end

function WindowMonster:Start(ctx)
	self:_invalidateSpots()
	self._state = "idle"
	self._retreatUntil = 0
	self._nextTeleport = 0
	self:_cancelClimb()

	self:Track(self._spotsFolder.ChildAdded:Connect(function()
		self:_invalidateSpots()
	end))
	self:Track(self._spotsFolder.ChildRemoved:Connect(function()
		self:_invalidateSpots()
	end))

	local spots = self:_spots()
	self._currentSpot = spots[math.random(1, #spots)]
	self._monster = self:_spawn(self._currentSpot)

	self:_armBreach(ctx)

	self:Track(ctx.Flash.Fired:Connect(function(player, cf, pos, spot)
		if self:_flashHits(player, cf, pos, spot) then
			self:_repel(player, ctx)
		end
	end))

	self:Log(("active @@U2014@@ %d spots (%d reached by climbing), flash-repel")
		:format(#spots, self._climbSpots or 0))
end

-- Spots changed: drop every cached answer about them.
function WindowMonster:_invalidateSpots()
	self._spotCache = nil
	self._classifyCache = nil
end

function WindowMonster:OnPhase(phase, ctx)
	-- re-roll the next teleport so escalation is felt immediately
	self._nextTeleport = 0
end

function WindowMonster:_repel(byPlayer, ctx)
	local wasClimbing = self._state == "climbing"
	self:_cancelClimb()
	self:_disarmBreach()
	if self._animator then
		self._animator:Play("recoil")
	end
	local cfg = self.Settings
	self._state = "hidden"
	if wasClimbing then
		self:Log("knocked off the wall")
	end

	local cooldown = self:ByIntensity(
		cfg.RetreatCooldownEasy, cfg.RetreatCooldownHard, ctx.Intensity)
	self._retreatUntil = os.clock() + cooldown

	setHidden(self._monster, true)

	local root = byPlayer and byPlayer.Character
		and byPlayer.Character:FindFirstChild("HumanoidRootPart")
	if root then
		local far = farthestFrom(root.Position, self:_spots()) or self._currentSpot
		self:_placeAt(self._monster, far)
		self._currentSpot = far
	end

	ctx.Director:Cue(byPlayer, {
		kind = "monsterRepelled",
		entity = self.Name,
		climbing = wasClimbing,
	})
end

function WindowMonster:_teleport(ctx)
	local cfg = self.Settings
	local spots = self:_spots()
	local newSpot = spots[math.random(1, #spots)]
	local tries = 0
	while newSpot == self._currentSpot and #spots > 1 and tries < 8 do
		newSpot = spots[math.random(1, #spots)]
		tries += 1
	end
	self:_goTo(newSpot, ctx)
	-- deliberately does NOT re-arm the breach timer: moving between windows is
	-- how it hunts, not a reprieve. Only a successful flash buys time back.
	-- (A climb pauses it for the duration instead @@U2014@@ see _startClimb.)

	local minWait = self:ByIntensity(cfg.TeleportMinEasy, cfg.TeleportMinHard, ctx.Intensity)
	local maxWait = self:ByIntensity(cfg.TeleportMaxEasy, cfg.TeleportMaxHard, ctx.Intensity)
	self._nextTeleport = os.clock() + minWait + math.random() * math.max(0, maxWait - minWait)
end

function WindowMonster:Update(dt, ctx)
	local monster = self._monster
	if not monster or not monster.Parent then
		return
	end

	local watching = self:_nearestPlayer()

	if self._animator then
		self._animator:SetIntensity(ctx.Intensity)
		self._animator:Update(dt, watching)
	end

	-- on the wall: the climb owns the body until it arrives, so nothing else
	-- below gets to move it or time it out
	if self._state == "climbing" then
		self:_updateClimb(dt, ctx)
		return
	end

	--[[
		Keep the BODY turned toward whoever is nearest, not just the head.

		The head is clamped to a human-ish arc, so if the body is pointing the
		wrong way the stare can never recover. Facing is set on spawn, but at
		night start the player's Character often has not replicated yet, so
		there is nobody to face and it ends up on a default heading. This turns
		it the rest of the way, slowly, and keeps it honest as the player moves.
	]]
	if watching and self._state == "idle" and monster.PrimaryPart then
		local pos = monster.PrimaryPart.Position
		local flat = Vector3.new(watching.X - pos.X, 0, watching.Z - pos.Z)
		if flat.Magnitude > 0.5 then
			local want = CFrame.lookAt(pos, pos + flat.Unit)
			monster:PivotTo(monster.PrimaryPart.CFrame:Lerp(
				want, math.clamp(dt * (self.Settings.TurnSpeed or 2), 0, 1)))
		end
	end
	local cfg = self.Settings
	local now = os.clock()

	if self._state == "hidden" then
		if now >= self._retreatUntil then
			setHidden(monster, false)
			self._state = "idle"
			self._nextTeleport = 0
			self:_armBreach(ctx)
			if self._animator then
				self._animator:Play("watch", true)
			end
		end
		return
	end

	-- breach countdown
	if self._breachAt and self._breachAt > 0 then
		local left = self._breachAt - now
		if left <= 0 then
			self:_breach(ctx)
			return
		end
		if not self._breachWarned
			and left <= (self._patience or 0) * self.Settings.BreachWarnAt then
			self._breachWarned = true
			ctx.Net.BroadcastCue({
				kind = "breachWarning",
				entity = self.Name,
				seconds = left,
			})
		end
	end

	if self._nextTeleport == 0 then
		local minWait = self:ByIntensity(cfg.TeleportMinEasy, cfg.TeleportMinHard, ctx.Intensity)
		local maxWait = self:ByIntensity(cfg.TeleportMaxEasy, cfg.TeleportMaxHard, ctx.Intensity)
		self._nextTeleport = now + minWait + math.random() * math.max(0, maxWait - minWait)
	elseif now >= self._nextTeleport then
		self:_teleport(ctx)
	end
end

function WindowMonster:Stop(ctx)
	self:_disarmBreach()
	self:_cancelClimb()
	if self._animator then
		self._animator:Destroy()
		self._animator = nil
	end
	self._monster = nil
	self:_invalidateSpots()
end

return WindowMonster

]=====]


local function repair(s)
	for token, bytes in pairs(FIX) do
		s = s:gsub(token, bytes)
	end
	return s
end

local function count(haystack, needle)
	local _, n = haystack:gsub(needle, "")
	return n
end

local nl = game:GetService("ServerScriptService"):FindFirstChild("NightLoop")
if not nl then
	return H:JSONEncode({ error = "no ServerScriptService.NightLoop - nothing pushed" })
end
local entities = nl:FindFirstChild("Entities")
if not entities then
	return H:JSONEncode({ error = "no ServerScriptService.NightLoop.Entities - nothing pushed" })
end

-- Replace a module: build the new instance FIRST, then drop the old one, so
-- the folder is never briefly without a module of that name.
local function put(parent, name, source)
	local old = parent:FindFirstChild(name)
	local inst = Instance.new("ModuleScript")
	inst.Name = name .. "__push"
	inst.Source = source
	inst.Parent = parent
	if old then
		old:Destroy()
	end
	inst.Name = name
	return inst
end

local written = {}
local function push(key, parent, name)
	local src = repair(SOURCES[key])
	local inst = put(parent, name, src)
	written[key] = inst
	return {
		name = name,
		path = inst:GetFullName(),
		bytes = #inst.Source,
		expect = EXPECT[key],
		bytesOk = #inst.Source == EXPECT[key],
		dashes = count(inst.Source, "\226\128\148"),
		dashesOk = count(inst.Source, "\226\128\148") == DASHES[key],
		dots = count(inst.Source, "\194\183"),
		dotsOk = count(inst.Source, "\194\183") == DOTS[key],
	}
end

local report = {
	pushed = {
		push("Config", nl, "Config"),
		push("MonsterAnimator", nl, "MonsterAnimator"),
		push("WindowMonster", entities, "WindowMonster"),
	},
}

-- Did it land, and does the new Config actually parse and expose the new
-- block? require() on a plugin thread is the cheapest way to know.
local okConfig, liveConfig = pcall(require, nl.Config)
local okEntity, liveEntity = pcall(require, entities.WindowMonster)
report.require = {
	config = okConfig,
	windowMonster = okEntity,
	configError = okConfig and nil or tostring(liveConfig),
	entityError = okEntity and nil or tostring(liveEntity),
}
if okConfig then
	local wm = liveConfig.Entities and liveConfig.Entities.WindowMonster
	local climb = wm and wm.Climbing
	report.climbing = {
		present = climb ~= nil,
		enabled = climb and climb.Enabled,
		speed = climb and climb.Speed,
		stride = climb and climb.Stride,
		grip = climb and climb.Grip,
		turnSpeed = wm and wm.TurnSpeed,
		requireGround = wm and wm.RequireGround,
		useBuiltInRig = wm and wm.UseBuiltInRig,
	}
end

local allOk = true
for _, entry in ipairs(report.pushed) do
	if not (entry.bytesOk and entry.dashesOk and entry.dotsOk) then
		allOk = false
	end
end
report.ok = allOk and okConfig and okEntity

return H:JSONEncode(report)
